from django.db import models

# Create your models here.
class Resume_Detail(models.Model):
    s_no = models.AutoField(primary_key = True)
    first_name = models.CharField(max_length = 50)
    last_name = models.CharField(max_length = 50)
    adm_no = models.CharField(max_length = 20)
    email = models.EmailField(max_length = 120)
    phn_no = models.CharField(max_length = 12)
    linkedin_id = models.CharField(max_length = 30)
    address = models.CharField(max_length = 300)
    state = models.CharField(max_length = 20)
    city = models.CharField(max_length = 20)
    zip_code = models.CharField(max_length = 8)
    career_objective = models.TextField(max_length = 300, null=True)
    tech_skills = models.CharField(max_length = 220)
    course = models.CharField(max_length = 10)
    branch = models.CharField(max_length = 10)
    university = models.CharField(max_length = 20)
    passing_year = models.CharField(max_length = 6)
    percent_academic = models.FloatField(null = True)
    board_secondary_school = models.CharField(max_length = 20)
    passing_year_secondary_school = models.CharField(max_length = 6)
    percent_secondary_school = models.FloatField(null = True)
    board_high_school = models.CharField(max_length = 20)
    passing_year_high_school = models.CharField(max_length = 6)
    percent_high_school = models.FloatField(null = True)
    university_diploma = models.CharField(max_length = 50)
    passing_year_diploma = models.CharField(max_length = 6)
    percent_diploma = models.FloatField(null = True)
    graduation_course = models.CharField(max_length = 20)
    university_other_graduation = models.CharField(max_length = 20)
    passing_year_other_graduation = models.CharField(max_length = 6)
    percent_other_graduation = models.FloatField(null = True)
    certificates = models.CharField(max_length = 400)
    internship_company_name = models.CharField(max_length = 50)
    internship_project_title = models.CharField(max_length = 50)
    internship_duration = models.IntegerField(null = True)
    internship_project_description = models.TextField(max_length = 200)
    interpersonal_skills = models.CharField(max_length = 300)
    achievements = models.CharField(max_length = 300)
    co_curriculars = models.CharField(max_length = 300)
    resume_reference_name = models.CharField(max_length = 50)
    resume_reference_designation = models.CharField(max_length = 30)
    resume_reference_organization = models.CharField(max_length = 60)

    def __str__(self):
        return self.first_name + " " + self.last_name
    