# Generated by Django 3.0.5 on 2020-06-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Detail',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('adm_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=120)),
                ('phn_no', models.CharField(max_length=12)),
                ('linkedin_id', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=300)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('zip_code', models.CharField(max_length=8)),
                ('career_objective', models.TextField()),
                ('tech_skills', models.CharField(max_length=220)),
                ('course', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
                ('university', models.CharField(max_length=20)),
                ('passing_year', models.CharField(max_length=6)),
                ('percent_academic', models.FloatField()),
                ('board_secondary_school', models.CharField(max_length=20)),
                ('passing_year_secondary_school', models.CharField(max_length=6)),
                ('percent_secondary_school', models.FloatField()),
                ('board_high_school', models.CharField(max_length=20)),
                ('passing_year_high_school', models.CharField(max_length=6)),
                ('percent_high_school', models.FloatField()),
                ('university_diploma', models.CharField(max_length=50)),
                ('passing_year_diploma', models.CharField(max_length=6)),
                ('percent_diploma', models.FloatField()),
                ('graduation_course', models.CharField(max_length=20)),
                ('university_other_graduation', models.CharField(max_length=20)),
                ('passing_year_other_graduation', models.CharField(max_length=6)),
                ('percent_other_graduation', models.FloatField()),
                ('certificates', models.CharField(max_length=400)),
                ('internship_company_name', models.CharField(max_length=50)),
                ('internship_project_title', models.CharField(max_length=50)),
                ('internship_duration', models.IntegerField()),
                ('internship_project_description', models.TextField(max_length=200)),
                ('interpersonal_skills', models.CharField(max_length=300)),
                ('achievements', models.CharField(max_length=300)),
                ('co_curriculars', models.CharField(max_length=300)),
                ('resume_reference_name', models.CharField(max_length=50)),
                ('resume_reference_designation', models.CharField(max_length=30)),
                ('resume_reference_organization', models.CharField(max_length=60)),
            ],
        ),
    ]
