# Generated by Django 3.0.5 on 2020-06-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_detail',
            name='internship_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resume_detail',
            name='percent_academic',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resume_detail',
            name='percent_diploma',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resume_detail',
            name='percent_high_school',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resume_detail',
            name='percent_other_graduation',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='resume_detail',
            name='percent_secondary_school',
            field=models.FloatField(default=0.0),
        ),
    ]
