# Generated by Django 3.0.7 on 2020-06-20 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200615_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_detail',
            name='career_objective',
            field=models.TextField(max_length=300),
        ),
    ]
