# Generated by Django 3.0.7 on 2020-06-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200620_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_detail',
            name='career_objective',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
