# Generated by Django 3.0.7 on 2020-06-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_auto_20200620_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume_detail',
            name='photo',
            field=models.ImageField(default='', upload_to='resume_profile_pics'),
        ),
    ]
