# Generated by Django 3.0.7 on 2020-06-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_resume_detail_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume_detail',
            name='user',
        ),
    ]
