# Generated by Django 3.0.7 on 2020-06-21 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resume', '0010_auto_20200622_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume_detail',
            name='photo',
            field=models.ImageField(upload_to='resume_profile_pics/'),
        ),
        migrations.AlterField(
            model_name='resume_detail',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
