# Generated by Django 3.0.7 on 2020-06-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20200626_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_coming',
            name='branches_to_reach',
        ),
    ]
