# Generated by Django 3.0.7 on 2020-06-26 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0007_remove_company_coming_branches_to_reach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_coming',
            name='students_applied',
        ),
        migrations.AlterField(
            model_name='company_coming',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
