# Generated by Django 3.0.7 on 2020-06-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        ('company', '0002_remove_company_coming_students_apporached'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_coming',
            name='students_applied',
            field=models.ManyToManyField(to='resume.Resume_Detail'),
        ),
    ]
