# Generated by Django 3.0.7 on 2020-06-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_coming_students_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_coming',
            name='job_description',
            field=models.TextField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
