# Generated by Django 3.0.7 on 2020-06-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20200627_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_coming',
            name='students_applied',
            field=models.CharField(default='', max_length=1500),
            preserve_default=False,
        ),
    ]
